# fly.toml app configuration file generated for gcna on 2024-06-19T18:58:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = 'gcna'
primary_region = 'mia'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[mounts]
  source="myapp_data"
  destination="/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "python manage.py migrate"

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
